version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:git
    steps:
      - checkout
      - run: echo "Initial testing should be here"
  jenkins:
    docker:
      - image: circleci/python
    steps:
      - deploy:
          name: Call Jenkins to continue workflow
          command: |
            curl -sL https://raw.githubusercontent.com/devops-workflow/aws-lambda-jenkins-proxy/master/integration-circleci-to-jenkins.sh | bash -s -- NAMESPACE
            # or
            #wget -qO- https://raw.githubusercontent.com/devops-workflow/aws-lambda-jenkins-proxy/master/integration-circleci-to-jenkins.sh | bash -s -- NAMESPACE
            # https://circleci.com/docs/2.0/env-vars/
workflows:
  version: 2
  node_workflow:
    jobs:
      - build
      - jenkins:
          context: org-global
          requires:
            - build
