# Example of running paralel jobs and passing the build numbers between jobs,
# so they can be passed to Jenkins
version: 2
jobs:
  eslint:
    working_directory: /root/repo
    docker:
      - image: docker:git
    steps:
      - checkout
      - run: |
          echo "Run ESLint"
          # Generate output (Formats: Checkstyle, JUnit)
          mkdir -p reports/junit
          cat <<EOF >reports/junit/eslint.xml
          <?xml version="1.0" encoding="utf-8"?>
          EOF
          cat <<EOF >reports/checkstyle.xml
          <?xml version="1.0" encoding="utf-8"?>
          EOF
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports
      - run: |
          mkdir -p workspace/build_nums
          echo "${CIRCLE_BUILD_NUM}" > workspace/build_nums/${CIRCLE_STAGE}.num
      - persist_to_workspace:
          root: workspace
          paths:
            - build_nums
  unittests:
    working_directory: /root/repo
    docker:
      - image: docker:git
    steps:
      - checkout
      - run: |
          echo "Run unit tests and code coverage"
          # Generate output (Formats: JUnit, Clover, LCOV, HTML)
          mkdir -p reports/junit reports/coverage/html
          cat <<EOF >reports/junit/unittests.xml
          <?xml version="1.0" encoding="utf-8"?>
          EOF
          cat <<EOF >reports/coverage/cobertura.xml
          <?xml version="1.0" encoding="utf-8"?>
          EOF
          cat <<EOF >reports/coverage/clover.xml
          <?xml version="1.0" encoding="utf-8"?>
          EOF
          cat <<EOF >reports/coverage/html/index.html
          <!doctype html>
          EOF
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports
      - run: |
          mkdir -p workspace/build_nums
          echo "${CIRCLE_BUILD_NUM}" > workspace/build_nums/${CIRCLE_STAGE}.num
      - persist_to_workspace:
          root: workspace
          paths:
            - build_nums
  jenkins:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Call Jenkins to continue workflow
          command: |
            curl -sSL https://raw.githubusercontent.com/devops-workflow/aws-lambda-jenkins-proxy/master/integration-circleci-to-jenkins-2.sh | bash -x -s -- NAMESPACE

workflows:
  version: 2
  ci:
    jobs:
      - eslint
      - unittests
      - jenkins:
          context: org-global
          requires:
            - unittests
            - eslint
